/* eslint-disable no-template-curly-in-string */
import { TCertsItems } from '@site/src/customTypes/certs'
import { CUSTOM_VALUE } from '@site/src/constants/kubernetes/customValue'

export const CERTIFICATES: TCertsItems = {
  etcdCA: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/ca.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/ca.crt`,
    csrPath: '',
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/etcd-ca.conf`,
    keySize: '2048',
    cname: 'etcd-ca',
  },
  kubernetesCA: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/ca.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/ca.crt`,
    csrPath: '',
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/ca.conf`,
    keySize: '2048',
    cname: 'kubernetes',
  },
  frontProxyCA: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/front-proxy-ca.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/front-proxy-ca.crt`,
    csrPath: '',
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/front-proxy-ca.conf`,
    keySize: '2048',
    cname: 'front-proxy-ca',
  },
  kubernetesControllerManagerClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/controller-manager-client-key.pem`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/controller-manager-client.pem`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/controller-manager-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/controller-manager-client.conf`,
    keySize: '2048',
    cname: 'system:kube-controller-manager',
  },
  kubernetesControllerManagerServer: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/controller-manager-server.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/controller-manager-server.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/controller-manager-server.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/controller-manager-server.conf`,
    keySize: '2048',
    cname: 'system:kube-controller-manager-server',
  },
  etcdClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/healthcheck-client.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/healthcheck-client.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/etcd-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/healthcheck-client.conf`,
    keySize: '2048',
    cname: 'kube-etcd-healthcheck-client',
  },
  etcdServer: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/server.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/server.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/etcd-server.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/etcd-server.conf`,
    keySize: '2048',
    cname: '', // dynamic
  },
  etcdPeer: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/peer.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/etcd/peer.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/etcd-peer.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/etcd-peer.conf`,
    keySize: '2048',
    cname: '', // dynamic
  },
  kubernetesKubeletClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver-kubelet-client.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver-kubelet-client.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/apiserver-kubelet-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/apiserver-kubelet-client.conf`,
    keySize: '2048',
    cname: 'kube-apiserver-kubelet-client',
  },
  kubernetesFrontProxyClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/front-proxy-client.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/front-proxy-client.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/front-proxy-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/front-proxy-client.conf`,
    keySize: '2048',
    cname: 'front-proxy-client',
  },
  kubernetesEtcdClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver-etcd-client.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver-etcd-client.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/apiserver-etcd-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/apiserver-etcd-client.conf`,
    keySize: '2048',
    cname: 'kube-apiserver-etcd-client',
  },
  kubernetesServer: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/apiserver.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/apiserver.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/apiserver.conf`,
    keySize: '2048',
    cname: 'kube-apiserver',
  },
  kubernetesSuperAdminClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/super-admin.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/super-admin.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/super-admin.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/super-admin.conf`,
    keySize: '2048',
    cname: 'kubernetes-super-admin',
  },
  kubernetesAdminClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/admin.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/admin.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/admin.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/admin.conf`,
    keySize: '2048',
    cname: 'kubernetes-admin',
  },
  kubernetesSA: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/sa.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/sa.pub`,
    csrPath: '',
    crtConf: '',
    keySize: '2048',
    cname: '',
  },
  kubeletClient: {
    keyPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-client-key.pem`,
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-client.pem`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/kubelet-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/kubelet-client.conf`,
    keySize: '2048',
    cname: '',
  },
  kubeletServer: {
    keyPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-server-key.pem`,
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-server.pem`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/kubelet-server.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/kubelet-server.conf`,
    keySize: '2048',
    cname: '',
  },
  kubeletCurrentClient: {
    keyPath: '',
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-client-current.pem`,
    csrPath: '',
    crtConf: '',
    keySize: '2048',
    cname: '',
  },

  kubeletNowClient: {
    keyPath: '',
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-client-$(date '+%Y-%m-%d-%H-%M-%S').pem`,
    csrPath: '',
    crtConf: '',
    keySize: '2048',
    cname: '',
  },
  kubeletCurrentServer: {
    keyPath: '',
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-server-current.pem`,
    csrPath: '',
    crtConf: '',
    keySize: '2048',
    cname: '',
  },
  kubeletNowServer: {
    keyPath: '',
    crtPath: `${CUSTOM_VALUE.kuberneteKubeletFolderPath.value}/pki/kubelet-server-$(date '+%Y-%m-%d-%H-%M-%S').pem`,
    csrPath: '',
    crtConf: '',
    keySize: '2048',
    cname: '',
  },
  kubernetesSchedulerClient: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/scheduler-client-key.pem`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/kubeconfig/scheduler-client.pem`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/scheduler-client.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/scheduler-client.conf`,
    keySize: '2048',
    cname: 'system:kube-scheduler',
  },
  kubernetesSchedulerServer: {
    keyPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/scheduler-server.key`,
    crtPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/pki/scheduler-server.crt`,
    csrPath: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/csr/scheduler-server.csr`,
    crtConf: `${CUSTOM_VALUE.kubernetesBaseFolderPath.value}/openssl/scheduler-server.conf`,
    keySize: '2048',
    cname: 'system:kube-scheduler-server',
  },
}
